language: java
sudo: required
jdk:
  - oraclejdk8
os:
  - linux
before_install:
 - chmod +x gradlew
install:
 - sudo apt-get install unzip -y
script:
 - ./gradlew assemble
 - ./gradlew check --info
notifications:
 slack:
  on_success: change
  on_failure: always
 email:
  - gam2046@gmail.com
  - gam2046@qq.com